name: Deploy WordPress

on:
  push:
    branches:
      - master  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy files to VPS

      - name: Deploy WordPress Files
        run: |
          EC2_USER=${{ secrets.VPS_USER }}
          BASTION_HOST=${{ secrets.BASTION_HOST }}
          PRIVATE_EC2=${{ secrets.VPS_HOST }}
          WORDPRESS_DIR=${{ secrets.VPS_WORDPRESS_DIR }}

          echo "Deploying WordPress files to $PRIVATE_EC2 via Bastion Host $BASTION_HOST"

          # Sync files via Bastion Host
          rsync -e "ssh -o ProxyCommand='ssh -W %h:%p $EC2_USER@$BASTION_HOST'" -avz --delete \
            ./ $EC2_USER@$PRIVATE_EC2:$WORDPRESS_DIR

        

      # Step 4: Reload the web server (optional)
      - name: Reload Nginx
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo systemctl reload nginx"

      # Optional: Notify success
      - name: Notify Deployment Success
        run: echo "WordPress deployment complete!"
